[package]
name = "nBodyProblem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-geometry = "0.8.3"
bracket-lib = "0.8.1"
